@extends('layouts.site')
@section('title', 'AI Agent — Loop')

@push('styles')
<link rel="stylesheet" href="{{ asset('vendor/public-website/assets/pages-base.css') }}">
@endpush

@section('content')
<section class="about-header"><div class="container"><div class="eyebrow">AI Agent</div><h1>An AI agent that answers, sells and knows when to hand off</h1><p>Train it on your own content. It replies only from verified sources and passes complex cases to your team with full context.</p><div class="hero-actions"><a href="{{ route('register') }}" class="btn btn-cobalt">Start free trial</a><a href="{{ url('/contact-sales') }}" class="btn btn-outline-ink">Contact sales</a></div></div></section>
<section class="sec tight"><div class="container"><div class="stat3"><div><b>67%</b><span>of chats resolved instantly*</span></div><div><b>30+</b><span>languages answered natively</span></div><div><b>0</b><span>guessing: it says "I don't know"</span></div></div></div></section><section class="sec"><div class="container"><h2 class="h2s">What you get</h2><div style="height:1rem"></div><div class="tile-grid" style="grid-template-columns:repeat(auto-fill,minmax(250px,1fr))"><div class="tile"><div class="ico"><i class="bi bi-patch-check"></i></div><h3>Data-backed answers</h3><p>Every reply is grounded in your site, help center and product data.</p></div><div class="tile"><div class="ico"><i class="bi bi-arrow-left-right"></i></div><h3>Honest handoffs</h3><p>When judgment is needed, it routes to the right person with the whole transcript.</p></div><div class="tile"><div class="ico"><i class="bi bi-lightning-charge"></i></div><h3>Smart actions</h3><p>Check an order, qualify a lead or book a call through your connected systems.</p></div><div class="tile"><div class="ico"><i class="bi bi-hand-thumbs-up"></i></div><h3>Product recommendations</h3><p>Suggests items from your live catalog, so advice matches what you sell.</p></div><div class="tile"><div class="ico"><i class="bi bi-translate"></i></div><h3>Multilanguage</h3><p>Detects each customer's language and answers naturally in it.</p></div><div class="tile"><div class="ico"><i class="bi bi-shield-lock"></i></div><h3>Guardrails and audit logs</h3><p>Set topics it must avoid and review every conversation afterwards.</p></div></div></div></section><section class="sec"><div class="container"><a class="tile glass" href="{{ url('/ai-agent-product-recommendations') }}" style="display:flex;align-items:center;gap:1rem;flex-wrap:wrap;justify-content:space-between"><div><span class="tag">New</span><h3 style="margin:0">Product recommendations</h3><p>See how the agent suggests items from your live catalog.</p></div><i class="bi bi-arrow-right" style="font-size:1.5rem"></i></a></div></section>
<section class="sec"><div class="container"><h2 class="h2s">How it works</h2><div style="height:1rem"></div><div class="tile-grid"><div class="tile"><div class="step-num">1</div><h3>Connect your knowledge</h3><p>Add your website, help articles and product data.</p></div><div class="tile"><div class="step-num">2</div><h3>Test in the playground</h3><p>Ask tricky questions and refine answers before going live.</p></div><div class="tile"><div class="step-num">3</div><h3>Go live and improve</h3><p>Review suggestions that raise resolution rate and satisfaction.</p></div></div></div></section><section class="sec"><div class="container"><h2 class="h2s">Common questions</h2><div style="height:1rem"></div><div class="accordion" id="ai"><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#ai0">Will it make things up?</button></h3><div id="ai0" class="accordion-collapse collapse" data-bs-parent="#ai"><div class="accordion-body">No. It answers only from your sources and hands over when unsure.</div></div></div><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#ai1">Can it take actions?</button></h3><div id="ai1" class="accordion-collapse collapse" data-bs-parent="#ai"><div class="accordion-body">Yes, through smart actions connected to your systems.</div></div></div><div class="accordion-item"><h3 class="accordion-header"><button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#ai2">*About the numbers</button></h3><div id="ai2" class="accordion-collapse collapse" data-bs-parent="#ai"><div class="accordion-body">Illustrative figures for this demo site.</div></div></div></div></div></section>
<section class="final-cta"><div class="container"><h2>What will your next 100 conversations earn?</h2><a href="{{ route('register') }}" class="btn btn-cobalt">Start for free</a><p style="margin-top:1rem;color:var(--ink-soft);font-size:.9rem">No credit card required</p></div></section>
@endsection
